language: python
sudo: disabled

python:
  - "3.5"

os:
  - linux

git:
  depth: 1

env:
  global:
    - RADICAL_PILOT_DBURL=mongodb://rct:rct_test@one.radical-project.org/rct_test
    - RADICAL_PILOT_TEST_DBNAME=rct_test
    - COVERAGE=false
    - CODECOV_TOKEN="c7e0d993-d31a-4d39-8ffa-07c30ea73e48"
  matrix:
    - MAIN_CMD="coverage run -m pytest -vvv tests/"
    - MAIN_CMD="tests/bin/run_check.sh flake8 diff"
    - MAIN_CMD="tests/bin/run_check.sh pylint diff"
    - MAIN_CMD="tests/bin/run_check.sh flake8 tests/ bin/ examples/"
    - MAIN_CMD="tests/bin/run_check.sh pylint tests/ bin/ examples/"

before_install:
  - uname -a
  - ulimit -a
  - python -V

# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install pylint
  - pip install codecov

script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD

after_success:
  - |
    if [[ $COVERAGE == 'true' ]]; then \
      coverage combine; \
      coverage xml; \
      coverage report; \
      curl -s https://codecov.io/bash | bash
    fi
notifications:
  email:
    recipients: andre@merzky.net
    on_success: change
    on_failure: always
