language: python
sudo: disabled

python:
  - "3.5"

os:
  - linux

git:
  depth: 1

env:
  global:
    - RADICAL_PILOT_DBURL=mongodb://rct:rct_test@one.radical-project.org/rct_test
    - RADICAL_PILOT_TEST_DBNAME=rct_test
    - LOG=`git log -n 1 | grep Merge`
    - OLD=`echo $LOG | cut -d ' ' -f2`
    - NEW=`echo $LOG | cut -d ' ' -f3`
    - DIFF=`git diff --name-only --diff-filter=b $OLD...$NEW`
    - DIFF=$(echo $DIFF | grep -o -e '\b[^ ]*.py\b')
    - LOC=/home/travis/virtualenv/python2.7  # Location where VE is created on travis
    - CMD_PYTEST="coverage run -m pytest -vvv tests/"
    - CMD_FLAKE8="for f in $DIFF; do echo test -f $f && flake8 --config=.flake8 $f; done"
    - CMD_PYLINT="for f in $DIFF; do echo test -f $$f && pylint $$f; done"
    - CMD_FLAKE8_OTHER="flake8 --config=.flake8 tests/ bin/ exmaples/"
    - CMD_PYLINT_OTHER="pylint tests/ bin/ examples/"
    - COVERAGE=false
    - CODECOV_TOKEN="c7e0d993-d31a-4d39-8ffa-07c30ea73e48"
  matrix:
    - MAIN_CMD=$CMD_PYTEST COVERAGE=true
    - MAIN_CMD=$CMD_FLAKE8
    - MAIN_CMD=$CMD_PYLINT
    - MAIN_CMD=$CMD_FLAKE8_OTHER
    - MAIN_CMD=$CMD_PYLINT_OTHER

before_install:
  - uname -a
  - ulimit -a
  - python -V

# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install pylint
  - pip install codecov


script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD

after_success:
  - |
    if [[ $COVERAGE == 'true' ]]; then \
      coverage combine; \
      coverage xml; \
      coverage report; \
      curl -s https://codecov.io/bash | bash
    fi
notifications:
  email:
    recipients: andre@merzky.net
    on_success: change
    on_failure: always
